<create_file>
<path>src/data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>_src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_baz_root.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>_src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>_src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<path>src.data_rpg_bazuka_data.js</path>
<_path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<_content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<content>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
<path>src.data_rpg_bazuka_data.js</path>
<create_file>
<create_file>
